site_name: MasterFacilityList Documentation
site_description: Documentation for the Kenyan MasterFacilityList
repo_url: https://github.com/masterfacilitylist/masterfacilitylist.github.io
copyright: Savannah Informatics Limited &copy; 2015
theme: readthedocs

pages:
  - ['index.md', 'Home']
